# Generated by Django 6.0.3 on 2026-05-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='study_year',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'مستخدم عادي'), ('reviewer', 'مراجع أكاديمي'), ('admin', 'مسؤول')], default='user', max_length=20),
        ),
    ]
