# Generated by Django 6.0.3 on 2026-05-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('font_size', models.CharField(help_text="e.g., '12pt Times New Roman'", max_length=50)),
                ('margins', models.CharField(help_text="e.g., '1 inch on all sides'", max_length=100)),
                ('line_spacing', models.CharField(help_text="e.g., 'Double-spaced'", max_length=50)),
                ('image_dimensions', models.CharField(help_text="e.g., 'Min 300 DPI, max 5 inches wide'", max_length=100)),
                ('citation_style', models.CharField(help_text="e.g., 'APA 7th Edition'", max_length=50)),
                ('max_word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('min_word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_requirements', models.TextField(blank=True, help_text='Any additional formatting requirements')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Guideline',
                'verbose_name_plural': 'Journal Guidelines',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='userpoints',
            name='eligible_for_cost_coverage',
            field=models.BooleanField(default=False, help_text='Flag for users eligible for publication cost support'),
        ),
        migrations.AlterField(
            model_name='pointtransaction',
            name='reason',
            field=models.CharField(choices=[('publish_article', 'نشر مقال (+10)'), ('receive_like', 'استقبال إعجاب (+2)'), ('receive_comment', 'استقبال تعليق (+1)'), ('receive_bookmark', 'حفظ في المفضلة (+3)'), ('expedite_review', 'استعجال تحكيم (-50)')], max_length=50),
        ),
    ]
