# Generated by Django 6.0.3 on 2026-05-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_abstract_alter_article_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='access_level',
        ),
        migrations.AddField(
            model_name='article',
            name='is_priority',
            field=models.BooleanField(default=False, help_text='Flag for expedited review requests'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('published', 'Published')], default='under_review', max_length=20),
        ),
    ]
