# Generated by Django 6.0.3 on 2026-05-29 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_access_level_article_is_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('field_of_study', models.CharField(max_length=255)),
                ('impact_factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('publication_type', models.CharField(choices=[('open_access', 'Open Access'), ('subscription', 'Subscription')], default='open_access', max_length=20)),
                ('publication_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('font_guidelines', models.TextField(blank=True)),
                ('margin_guidelines', models.TextField(blank=True)),
                ('figure_guidelines', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'ordering': ['-impact_factor'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='external_journal_accepted',
            field=models.BooleanField(default=False, help_text='Whether article has been accepted by external journal'),
        ),
        migrations.AddField(
            model_name='article',
            name='external_journal_name',
            field=models.CharField(blank=True, help_text='Name of external journal that accepted the article', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='subsidy_status',
            field=models.CharField(choices=[('not_eligible', 'Not Eligible'), ('pending_review', 'Pending Review'), ('approved_for_cost_coverage', 'Approved for Cost Coverage')], default='not_eligible', help_text='Subsidy eligibility status based on user points', max_length=30),
        ),
        migrations.AddField(
            model_name='article',
            name='nominated_journal',
            field=models.ForeignKey(blank=True, help_text='Journal nominated by reviewer or admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominated_articles', to='articles.journal'),
        ),
    ]
