# Generated by Django 6.0.3 on 2026-06-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_workflow_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='additional_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='citation_style',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='journal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='issn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='journal',
            name='max_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='max_word_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='min_word_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='journal',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
