# Generated by Django 6.0.3 on 2026-05-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('reviews', '0002_alter_review_options_reviewrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('issn', models.CharField(help_text='International Standard Serial Number', max_length=50, unique=True)),
                ('field_of_study', models.CharField(help_text='Primary field of study', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='journals', to='categories.category')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'ordering': ['title'],
            },
        ),
    ]
